- name: set up nginx
  become: true
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - nginx

# ------------------------------------------------------------------------ #

# static sites:
# - apt
# - codex
# - dl
# - hlml
# - kyleisom
# - lambda
# - lux.static
# - p

# proxy sites:
# - ghost
# - lamondetourne
# - lemondetourne
# - lux
# - perkeep


- name: setup kyleisom.net
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/kyleisom
    mode: 0644
    owner: www-data
  vars:
    context:
      name: "kyleisom.net www.kyleisom.net"
      siteroot: /home/kyle/sites/home
      cloudflare: false
      ssl: true
      certbot: kyleisom.net

- name: setup devlog site
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/dl
    mode: 0644
    owner: www-data
  vars:
    context:
      name: dl.kyleisom.net
      siteroot: /home/kyle/sites/dl
      cloudflare: false
      ssl: true
      certbot: kyleisom.net

- name: setup perkeep site
  become: true
  notify: restart nginx
  template:
    src: nginx-proxy.j2
    dest: /etc/nginx/sites-enabled/perkeep
    mode: 0644
    owner: www-data
  vars:
    context:
      name: data.kyleisom.net
      cloudflare: false
      upstream: 127.0.0.1:3179
      ssl: true
      certbot: data.kyleisom.net

- name: copy perkeep unit file
  become: true
  register: perkeep_svc
  copy:
    src: perkeep.service
    dest: /etc/systemd/system/perkeep.service
    owner: root
    group: root
    mode: 0644

- name: ensure perkeep service is running
  become: true
  when: perkeep_svc.changed
  systemd:
    daemon_reload: yes
    enabled: yes
    name: perkeep.service
    state: restarted

- name: run certbot renewal checks
  become: true
  cron:
    weekday: 6
    hour: 3
    minute: 0
    name: certbot-renewal
    job: certbot renew
    state: present
