- name: set up nginx
  become: true
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - nginx

- name: run certbot renewal checks
  become: true
  cron:
    weekday: 6
    hour: 3
    minute: 0
    name: certbot-renewal
    job: certbot renew -n
    state: present

# ------------------------------------------------------------------------ #

# static sites:
# - apt
# - codex
# - hlml
# - lambda
# - lux.static
# - p

# proxy sites:
# - ghost
# - lamondetourne
# - lemondetourne
# - lux

- name: setup kyleisom.net
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/kyleisom
    mode: 0644
    owner: www-data
  vars:
    context:
      name: "kyleisom.net www.kyleisom.net"
      siteroot: /home/kyle/sites/home
      cloudflare: false
      ssl: true
      certbot: kyleisom.net

- name: setup devlog site
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/dl
    mode: 0644
    owner: www-data
  vars:
    context:
      name: dl.kyleisom.net
      siteroot: /home/kyle/sites/dl
      cloudflare: false
      ssl: true
      certbot: kyleisom.net

- name: setup yaklog
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/yaklog
    mode: 0644
    owner: www-data
  vars:
    context:
      name: yak.kyleisom.net
      siteroot: /home/kyle/sites/yak
      cloudflare: false
      ssl: true
      certbot: lambda.kyleisom.net

- name: setup lambda
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/lambda
    mode: 0644
    owner: www-data
  vars:
    context:
      name: lambda.kyleisom.net
      siteroot: /home/kyle/sites/lambda
      cloudflare: false
      ssl: true
      certbot: lambda.kyleisom.net

- name: setup paste
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/p
    mode: 0644
    owner: www-data
  vars:
    context:
      name: p.kyleisom.net
      siteroot: /home/kyle/sites/p
      cloudflare: false
      ssl: true
      certbot: p.kyleisom.net

- name: setup unix-notes
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/unix-notes
    mode: 0644
    owner: www-data
  vars:
    context:
      name: unix.kyleisom.net
      siteroot: /home/kyle/sites/unix-notes
      cloudflare: false
      ssl: true
      certbot: unix.kyleisom.net

- name: setup irc front
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/irc
    mode: 0644
    owner: www-data
  vars:
    context:
      name: irc.tyrfingr.is
      siteroot: /home/kyle/sites/irc
      cloudflare: false
      ssl: true
      certbot: irc.tyrfingr.is 

- name: setup lisp docs
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/codex
    mode: 0644
    owner: www-data
  vars:
    context:
      name: codex.metacircular.net
      siteroot: /home/kyle/sites/codex
      cloudflare: true
      ssl: true
      certbot: codex.metacircular.net

- name: setup notebook
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/notebook
    mode: 0644
    owner: www-data
  vars:
    context:
      name: notes.kyleisom.net
      siteroot: /home/kyle/sites/notebook
      cloudflare: false
      ssl: true
      certbot: notes.kyleisom.net

- import_tasks: perkeep.yaml
- import_tasks: ghost.yaml
