- name: set up nginx
  become: true
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - nginx

- name: run certbot renewal checks
  become: true
  cron:
    weekday: 6
    hour: 3
    minute: 0
    name: certbot-renewal
    job: certbot renew
    state: present

# ------------------------------------------------------------------------ #

# static sites:
# - apt
# - codex
# - hlml
# - lambda
# - lux.static
# - p

# proxy sites:
# - ghost
# - lamondetourne
# - lemondetourne
# - lux

- name: setup kyleisom.net
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/kyleisom
    mode: 0644
    owner: www-data
  vars:
    context:
      name: "kyleisom.net www.kyleisom.net"
      siteroot: /home/kyle/sites/home
      cloudflare: false
      ssl: true
      certbot: kyleisom.net

- name: setup devlog site
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/dl
    mode: 0644
    owner: www-data
  vars:
    context:
      name: dl.kyleisom.net
      siteroot: /home/kyle/sites/dl
      cloudflare: false
      ssl: true
      certbot: kyleisom.net

- name: setup yaklog
  become: true
  notify: restart nginx
  template:
    src: nginx-static.j2
    dest: /etc/nginx/sites-enabled/yaklog
    mode: 0644
    owner: www-data
  vars:
    context:
      name: yak.kyleisom.net
      siteroot: /home/kyle/sites/yak
      cloudflare: false
      ssl: false
      certbot: yak.kyleisom.net

- include: perkeep.yaml
